# basic options
title: rleeAI
author: 이승재
email: seungjl@princeton.edu
description: 강화학습
github_username:  seungjaeryanlee
linkedin_username: seungjaeryanlee

# Build settings
markdown: kramdown
theme: minima

permalink: /:categories/:title

plugins:
  - jekyll-feed
  - jekyll-redirect-from
